org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process

# 本机 SDK 是 android-37.0（带扩展版本），如果 AGP 对新版本报警告就打开下面这行
# android.suppressUnsupportedCompileSdk=37
